/**
 * Wiki Lint 脚本 v1.0
 * 移植自 lewislulu/llm-wiki-skill 的 lint_wiki.py（零外部依赖）
 * 7 轮健康检查 + --fix 自动修复 + --audit 生成审计文件
 *
 * 用法：
 *   node wiki-lint.js              # 运行全部 7 轮检查
 *   node wiki-lint.js --fix        # 自动修复可修复项
 *   node wiki-lint.js --audit      # 不可修复项生成审计文件到 .wiki/audit/
 *   node wiki-lint.js --pass 1     # 只运行第 1 轮
 *   node wiki-lint.js --test       # 运行内置测试
 */

'use strict';

const fs = require('fs');
const path = require('path');
const { parseFrontmatter, extractWikiLinks, isValidAuditFilename, validateAuditFrontmatter, AUDIT_TYPES, AUDIT_SEVERITIES, AUDIT_STATUSES, AUDIT_ACTIONS } = require('./wiki-utils');

// ============ 配置 ============
const WIKI_DIR = path.join(__dirname, '..', '.wiki');
const CONCEPTS_DIR = path.join(WIKI_DIR, 'concepts');
const ENTITIES_DIR = path.join(WIKI_DIR, 'entities');
const RAW_DIR = path.join(WIKI_DIR, 'raw');
const INDEX_FILE = path.join(WIKI_DIR, 'index.md');
const LOG_FILE = path.join(WIKI_DIR, 'log.md');
const AUDIT_DIR = path.join(WIKI_DIR, 'audit');
const WIKI_INDEX_JSON = path.join(WIKI_DIR, 'wiki-index.json');
const LAYER_DIRS = ['concepts', 'entities', 'comparisons', 'queries'];

// ============ 参数解析 ============
const args = process.argv.slice(2);
const FIX_MODE = args.includes('--fix');
const AUDIT_MODE = args.includes('--audit');
const RUN_TEST = args.includes('--test');
const PASS_INDEX = args.indexOf('--pass');
const TARGET_PASS = PASS_INDEX !== -1 && args[PASS_INDEX + 1] ? parseInt(args[PASS_INDEX + 1]) : null;

// ============ 结果收集 ============
const results = {
  pass1_dead_links: [],
  pass2_orphan_pages: [],
  pass3_missing_index: [],
  pass4_high_freq_unbuilt: [],
  pass5_log_format: [],
  pass6_audit_format: [],
  pass7_audit_target: [],
  fixed: 0,
  audits_generated: 0,
};

// ============ 工具函数 ============

/** 扫描所有 wiki 页面，返回 [{ title, file, layer, frontmatter, body }] */
function scanWikiPages() {
  const pages = [];

  function scan(dir) {
    if (!fs.existsSync(dir)) return;
    const items = fs.readdirSync(dir);
    for (const item of items) {
      const full = path.join(dir, item);
      const stat = fs.statSync(full);
      if (stat.isDirectory()) {
        scan(full);
      } else if (item.endsWith('.md') && item !== 'index.md' && item !== 'README.md') {
        const content = fs.readFileSync(full, 'utf-8');
        const { frontmatter, body } = parseFrontmatter(content);
        const title = frontmatter.title || path.basename(item, '.md');
        const layer = path.basename(dir);
        pages.push({ title, file: full, layer, frontmatter, body });
      }
    }
  }

  [CONCEPTS_DIR, ENTITIES_DIR].forEach(scan);
  return pages;
}

/** 构建标题→页面映射 */
function buildTitleIndex(pages) {
  const index = {};
  for (const page of pages) {
    index[page.title] = page;
  }
  return index;
}

/** 从 wiki-index.json 加载索引 */
function loadWikiIndexJson() {
  try {
    return JSON.parse(fs.readFileSync(WIKI_INDEX_JSON, 'utf-8'));
  } catch {
    return [];
  }
}

/** 获取下一个审计 ID */
function getNextAuditId() {
  const year = new Date().getFullYear();
  if (!fs.existsSync(AUDIT_DIR)) return `AUDIT-${year}-001`;

  const files = fs.readdirSync(AUDIT_DIR).filter(f => f.startsWith(`AUDIT-${year}`));
  let maxNum = 0;
  for (const f of files) {
    const match = f.match(/AUDIT-\d{4}-(\d{3})/);
    if (match) maxNum = Math.max(maxNum, parseInt(match[1]));
  }
  return `AUDIT-${year}-${String(maxNum + 1).padStart(3, '0')}`;
}

/** 生成审计文件 */
function generateAuditFile(target, type, severity, comment, suggestedAction) {
  if (!AUDIT_MODE) return;

  const id = getNextAuditId();
  const today = new Date().toISOString().split('T')[0];
  const content = `---
id: ${id}
target: "[[${target}]]"
type: ${type}
severity: ${severity}
status: open
comment: "${comment}"
suggested_action: ${suggestedAction}
created: ${today}
resolved:
resolved_by:
---

Auto-generated by wiki-lint.js on ${today}.
`;

  const filePath = path.join(AUDIT_DIR, `${id}.md`);
  fs.writeFileSync(filePath, content, 'utf-8');
  results.audits_generated++;
  console.log(`  📝 生成审计: ${id} → [[${target}]] (${type}/${severity})`);
}

// ============ Pass 1: 死链检测 ============

function pass1_deadLinks(pages, titleIndex) {
  console.log('\n🔍 Pass 1: 死链检测');

  for (const page of pages) {
    const links = extractWikiLinks(page.body);
    for (const target of links) {
      if (!titleIndex[target]) {
        // 大小写不敏感检查
        const lowerTarget = target.toLowerCase();
        const found = Object.keys(titleIndex).find(t => t.toLowerCase() === lowerTarget);
        if (!found) {
          results.pass1_dead_links.push({ page: page.title, target });
          console.log(`  ❌ 死链: [[${target}]] (来自 [[${page.title}]])`);
          generateAuditFile(target, 'dead_link', 'major', `[[${target}]] 被 [[${page.title}]] 引用但不存在`, 'fix_link');
        }
      }
    }
  }

  if (results.pass1_dead_links.length === 0) {
    console.log('  ✅ 无死链');
  }
}

// ============ Pass 2: 孤儿页 ============

function pass2_orphanPages(pages, titleIndex) {
  console.log('\n🔍 Pass 2: 孤儿页检测');

  // 构建入链索引
  const inLinks = {};
  for (const page of pages) {
    inLinks[page.title] = 0;
  }

  for (const page of pages) {
    const links = extractWikiLinks(page.body);
    for (const target of links) {
      if (inLinks[target] !== undefined) {
        inLinks[target]++;
      }
    }
  }

  // 排除 index 和 summary 页面
  const excludePatterns = [/^index$/i, /^summary$/i, /^README$/i];

  for (const [title, count] of Object.entries(inLinks)) {
    if (count === 0 && !excludePatterns.some(p => p.test(title))) {
      results.pass2_orphan_pages.push({ title });
      console.log(`  ⚠️  孤儿页: [[${title}]] (无入链)`);
      generateAuditFile(title, 'structure', 'minor', `[[${title}]] 无入链，可能需要添加引用`, 'add_content');
    }
  }

  if (results.pass2_orphan_pages.length === 0) {
    console.log('  ✅ 无孤儿页');
  }
}

// ============ Pass 3: 缺失索引条目 ============

function pass3_missingIndex(pages) {
  console.log('\n🔍 Pass 3: 缺失索引条目');

  const indexJson = loadWikiIndexJson();
  const indexedTitles = new Set(indexJson.map(i => i.title));
  let fixed = 0;

  for (const page of pages) {
    if (!indexedTitles.has(page.title)) {
      results.pass3_missing_index.push({ title: page.title });
      console.log(`  ⚠️  缺失索引: [[${page.title}]]`);

      if (FIX_MODE) {
        // 重新生成 wiki-index.json（由 wiki-compile.js 负责）
        console.log(`    🔧 --fix 模式：建议运行 node scripts/wiki-compile.js 重新生成索引`);
        fixed++;
      }
    }
  }

  results.fixed += fixed;

  if (results.pass3_missing_index.length === 0) {
    console.log('  ✅ 索引完整');
  }
}

// ============ Pass 4: 高频未建页概念 ============

function pass4_highFreqUnbuilt(pages, titleIndex) {
  console.log('\n🔍 Pass 4: 高频未建页概念 (≥3次引用)');

  const linkCounts = {};

  for (const page of pages) {
    const links = extractWikiLinks(page.body);
    for (const target of links) {
      if (!titleIndex[target]) {
        linkCounts[target] = (linkCounts[target] || 0) + 1;
      }
    }
  }

  // 筛选 ≥3 次的
  const highFreq = Object.entries(linkCounts)
    .filter(([, count]) => count >= 3)
    .sort((a, b) => b[1] - a[1]);

  for (const [target, count] of highFreq) {
    results.pass4_high_freq_unbuilt.push({ target, count });
    console.log(`  📌 高频未建页: [[${target}]] (${count}次引用)`);
    generateAuditFile(target, 'completeness', 'major', `被引用${count}次但无对应wiki页面`, 'add_content');
  }

  if (results.pass4_high_freq_unbuilt.length === 0) {
    console.log('  ✅ 无高频未建页');
  }
}

// ============ Pass 5: 日志格式检查 ============

function pass5_logFormat() {
  console.log('\n🔍 Pass 5: 日志格式检查');

  if (!fs.existsSync(LOG_FILE)) {
    console.log('  ⚠️  log.md 不存在');
    return;
  }

  const content = fs.readFileSync(LOG_FILE, 'utf-8');
  const lines = content.split('\n');
  const logRegex = /^-\s+\d{4}-\d{2}-\d{2}\s+\d{2}:\d{2}:\d{2}\s*\|/;
  let malformed = 0;

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i].trim();
    if (line.startsWith('- ') && !logRegex.test(line)) {
      results.pass5_log_format.push({ line: i + 1, content: line.slice(0, 80) });
      console.log(`  ⚠️  格式错误行 ${i + 1}: ${line.slice(0, 60)}...`);
      malformed++;
    }
  }

  if (malformed === 0) {
    console.log('  ✅ 日志格式正确');
  }
}

// ============ Pass 6: 审计文件格式检查 ============

function pass6_auditFormat() {
  console.log('\n🔍 Pass 6: 审计文件格式检查');

  if (!fs.existsSync(AUDIT_DIR)) {
    console.log('  ℹ️  audit/ 目录不存在，跳过');
    return;
  }

  const files = fs.readdirSync(AUDIT_DIR).filter(f => f.endsWith('.md') && f !== 'README.md');
  let malformed = 0;

  for (const file of files) {
    // 检查文件名格式
    if (!isValidAuditFilename(file)) {
      results.pass6_audit_format.push({ file, issue: '文件名格式错误' });
      console.log(`  ⚠️  文件名格式错误: ${file}`);
      malformed++;
      continue;
    }

    // 检查 frontmatter
    const content = fs.readFileSync(path.join(AUDIT_DIR, file), 'utf-8');
    const { frontmatter } = parseFrontmatter(content);
    const validation = validateAuditFrontmatter(frontmatter);

    if (!validation.valid) {
      results.pass6_audit_format.push({ file, issue: `缺失字段: ${validation.missing.join(', ')}` });
      console.log(`  ⚠️  ${file}: 缺失字段 ${validation.missing.join(', ')}`);

      if (FIX_MODE && validation.missing.length > 0) {
        // 尝试自动修复缺失字段
        console.log(`    🔧 --fix 模式：审计文件需手动修复`);
      }
      malformed++;
    }
  }

  if (malformed === 0 && files.length > 0) {
    console.log(`  ✅ ${files.length} 个审计文件格式正确`);
  } else if (files.length === 0) {
    console.log('  ℹ️  无审计文件');
  }
}

// ============ Pass 7: 审计目标文件存在性 ============

function pass7_auditTargetExists(pages) {
  console.log('\n🔍 Pass 7: 审计目标文件存在性');

  if (!fs.existsSync(AUDIT_DIR)) {
    console.log('  ℹ️  audit/ 目录不存在，跳过');
    return;
  }

  const titleIndex = buildTitleIndex(pages);
  const files = fs.readdirSync(AUDIT_DIR).filter(f => f.endsWith('.md') && f !== 'README.md');
  let invalid = 0;

  for (const file of files) {
    const content = fs.readFileSync(path.join(AUDIT_DIR, file), 'utf-8');
    const { frontmatter } = parseFrontmatter(content);

    if (frontmatter.target) {
      // 提取 WikiLink 中的标题
      const targetMatch = frontmatter.target.match(/\[\[([^\]]+)\]\]/);
      if (targetMatch) {
        const targetTitle = targetMatch[1];
        if (!titleIndex[targetTitle]) {
          results.pass7_audit_target.push({ file, target: targetTitle });
          console.log(`  ⚠️  ${file}: 目标 [[${targetTitle}]] 不存在`);

          if (FIX_MODE && frontmatter.status !== 'resolved' && frontmatter.status !== 'dismissed') {
            // 如果目标不存在且审计未解决，标记为 dismissed
            const filePath = path.join(AUDIT_DIR, file);
            let fileContent = fs.readFileSync(filePath, 'utf-8');
            fileContent = fileContent.replace('status: open', 'status: dismissed');
            fileContent = fileContent.replace('status: in_progress', 'status: dismissed');
            fs.writeFileSync(filePath, fileContent, 'utf-8');
            console.log(`    🔧 --fix: 已标记为 dismissed`);
            results.fixed++;
          }
          invalid++;
        }
      }
    }
  }

  if (invalid === 0 && files.length > 0) {
    console.log(`  ✅ 所有审计目标存在`);
  } else if (files.length === 0) {
    console.log('  ℹ️  无审计文件');
  }
}

// ============ 主逻辑 ============

function main() {
  console.log('\n🔧 Wiki Lint 脚本 v1.0');
  console.log('   移植自 lewislulu/llm-wiki-skill lint_wiki.py\n');

  if (FIX_MODE) console.log('🔧 --fix 模式：自动修复可修复项\n');
  if (AUDIT_MODE) console.log('📝 --audit 模式：生成审计文件\n');

  // 确保 audit 目录存在
  if (AUDIT_MODE && !fs.existsSync(AUDIT_DIR)) {
    fs.mkdirSync(AUDIT_DIR, { recursive: true });
  }

  const pages = scanWikiPages();
  const titleIndex = buildTitleIndex(pages);
  console.log(`📚 扫描到 ${pages.length} 个 wiki 页面\n`);

  // 运行检查
  const passes = [
    { num: 1, fn: () => pass1_deadLinks(pages, titleIndex) },
    { num: 2, fn: () => pass2_orphanPages(pages, titleIndex) },
    { num: 3, fn: () => pass3_missingIndex(pages) },
    { num: 4, fn: () => pass4_highFreqUnbuilt(pages, titleIndex) },
    { num: 5, fn: () => pass5_logFormat() },
    { num: 6, fn: () => pass6_auditFormat() },
    { num: 7, fn: () => pass7_auditTargetExists(pages) },
  ];

  for (const pass of passes) {
    if (TARGET_PASS === null || TARGET_PASS === pass.num) {
      pass.fn();
    }
  }

  // 打印汇总
  console.log('\n========================================');
  console.log('📊 Lint 汇总');
  console.log('========================================');
  console.log(`  Pass 1 死链:       ${results.pass1_dead_links.length}`);
  console.log(`  Pass 2 孤儿页:     ${results.pass2_orphan_pages.length}`);
  console.log(`  Pass 3 缺失索引:   ${results.pass3_missing_index.length}`);
  console.log(`  Pass 4 高频未建页: ${results.pass4_high_freq_unbuilt.length}`);
  console.log(`  Pass 5 日志格式:   ${results.pass5_log_format.length}`);
  console.log(`  Pass 6 审计格式:   ${results.pass6_audit_format.length}`);
  console.log(`  Pass 7 审计目标:   ${results.pass7_audit_target.length}`);

  const totalIssues = results.pass1_dead_links.length + results.pass2_orphan_pages.length +
    results.pass3_missing_index.length + results.pass4_high_freq_unbuilt.length +
    results.pass5_log_format.length + results.pass6_audit_format.length + results.pass7_audit_target.length;

  console.log(`  ────────────────────────────`);
  console.log(`  总问题数:         ${totalIssues}`);
  if (FIX_MODE) console.log(`  已修复:           ${results.fixed}`);
  if (AUDIT_MODE) console.log(`  审计生成:         ${results.audits_generated}`);

  if (totalIssues > 0) {
    console.log('\n💡 运行 --fix 自动修复 | --audit 生成审计文件');
  } else {
    console.log('\n✅ 知识库健康！');
  }
}

// ============ 启动 ============

if (RUN_TEST) {
  console.log('🧪 Wiki Lint 测试（由 jest 覆盖，请运行 npm test）');
  process.exit(0);
} else {
  main();
}
